### ISSUE TITLE
ValueError: Unknown layer: Functional

### ISSUE THREAD

**Issue by OliviaZhang1996** [rozumden/FMODetect#1]
Hi, Rozumnyi.
Excellent work!
Can you provide the versions of your tensorflow, keras and h5py? Cause I meet the issue of "ValueError: Unknown layer: Functional" when loading the FMODetect.h5 model at the 25 line of run.py.
Thanks a lot.

**Comment by YuJiZhe** [comment]
> Hi, Rozumnyi. Excellent work! Can you provide the versions of your tensorflow, keras and h5py? Cause I meet the issue of "ValueError: Unknown layer: Functional" when loading the FMODetect.h5 model at the 25 line of run.py. Thanks a lot.

Hi friend, Did u solve this problem?

**Comment by rozumden** [comment]
Hi @olivia1823,

Thank you! I'm sorry for the late answer (due to some personal reasons). Below I provide the versions:
tensorflow==1.13.1
tf.keras is the default one in this TensorFlow version 
h5py==2.6.0

I believe the model loading will not work with other Tensorflow versions, unfortunately. Please let me know if this works.

**Comment by ItsMeAbby** [comment]
hi @rozumden 
The issue still prevails. Model is not being load.
Btw, pip install h5py==2.6.0 didn't work, used conda install -c clg_boar h5py

**Comment by wild10** [comment]
is someone who reproduces the experiments? or had successfully run the inference? if so please could you share with me the weights of the model

**Comment by 105nuuimgt** [comment]
> is someone who reproduces the experiments? or had successfully run the inference? if so please could you share with me the weights of the model

I tried to set the keras version to 2.4.0 and it works, you can try it

**Comment by wild10** [comment]
after sometime i run again successfully this using this setting.
python 3.7.4, h5py 2.10.0, tensorflow 2.11.0 and imageio 2.6.0, hope this help :)

**Comment by StephenZhao1** [comment]
anyone reimplement this algorithm with pytorch?
