### ISSUE TITLE
'TDF ' formula

### ISSUE THREAD

**Issue by Gi-gigi** [rozumden/FMODetect#2]
Does anyone know how the TDF(truncated distance function)  formula are written?

**Comment by rozumden** [comment]
Hi @Gigigi77, 

it's written in [dataset](https://github.com/rozumden/FMODetect/tree/master/dataset)/process_dataset_traj.py , in function get_data_processed() Line 213-215, where we apply the distance transform and truncate it by the value that equals to the object diameter (2*rad). Please note that the TDF is only calculated for the training dataset and it's not directly written in the network architecture. It's more like an output representation.

Best,
Denys

**Comment by Gi-gigi** [comment]
Thank u so much, sir! @rozumden .
Thanks for the pointer. Meanwhile, I read your words`"Please note that the TDF is only calculated for the training dataset and it's not directly written in the network architecture. "`,  But i really didn't understand how to run the file `train.py`, because I really want to try to debug it to see the details of the TDF(truncated distance function) related code. I see that this project cannot perform python `trian.py`.  Can u give me some advice, thank you.
Best,
Gigigi

**Comment by Gi-gigi** [comment]
> Please note that the TDF is only calculated for the training dataset and it's not directly written in the network architecture. It's more like an output representation.

oh! sorry!!!! i made a mistake, i want to know how to run `process_dataset_traj.py`,  because i can not get the document about `"votfmomedtraj_inputs.hdf5", "votfmomedtraj.hdf5" 
and
    parser.add_argument("--bg_path", required=True)
    parser.add_argument("--fg_path", required=True)
    parser.add_argument("--dataset_path", required=True)
    parser.add_argument("--dataset_size", type=int, required=True)
` this data in unknow, can u give me some advice to solve this problem? thank u agin~! sir

**Comment by rozumden** [comment]
@Gigigi77 in the dataset subfolder there is a script generate_dataset.sh. First, it will download the VOT dataset for background images. Second, it will generate foreground images (patterns). Lastly, it will combine both with random trajectories to generate training data. Have you managed to run this script?

**Comment by Gi-gigi** [comment]
Mr, @rozumden 
Hi, sir. I am glad you can reply me.

In `generate_dataset.sh` , I update 'BASE_PATH' to my path,
when i run  `sudo bash generate_dataset.sh`
The following TWO problem occurred：
`bash: trackdat/scripts/download_vot.sh: have no this file or  directory`
`bash: trackdat/scripts/unpack_vot.sh: have no this file or  directory`

These two files are not provided in the folder, 
so I found a ready-made` VOT2016 dataset` on the Internet, which includes 60 categories of video frames.
I run the two scripts separately  `generate_patterns.py` and `process_dataset_traj.py`
when i run `'process_dataset_traj.py --bg_path ${BG_PATH} --fg_path ${PATTERNS_PATH} --dataset_path ${DATASET_PATH} --dataset_size 5000',` I found a problem, i did not know how to get this `'DATASET_PATH="${BASE_PATH}/votfmomedtraj_inputs.hdf5"'`.
In `generate_dataset.sh`, There is no prompt to tell you how to get this file, and there is no such file in the project, and I am discouraged.

Let me summarize two problems: 
1. The resources 'download_vot.sh' and 'unpack_vot.sh' provided on the Internet [https://github.com/jvlmdr/trackdat](url) cannot download VOT2016. I found a ready-made data set on other website in China and used it directly. 
2. Not sure how to get this file `votfmomedtraj_inputs.hdf5` to run `process_dataset_traj.py`.

can u give me some advice again sir, i am very sorry to bother you. Thank u very much, sir!

**Comment by rozumden** [comment]
As mentioned in README, please clone the repository recursively (so that you also close trackdat repository): git clone --recursive git@github.com:rozumden/FMODetect.git

Script `process_dataset_traj.py` will generate `votfmomedtraj_inputs.hdf5`, you don't need to provide it.

**Comment by Gi-gigi** [comment]
Sorry sir.  @rozumden. The project zip package I downloaded directly from the webpage before.
Meanwhile I try my best, but i did not solve this probelm. I really don't want to bother you, but I really didn't think of a solution.

Firstly, I follow your instructions and `README` 
`git clone --recursive [git@github.com](mailto:git@github.com):rozumden/FMODetect.git`;
and then `sudo bash generate_dataset.sh`
Finally, some errors occurred as follow:

```
bash: trackdat/scripts/download_vot.sh: 没有那个文件或目录
bash: trackdat/scripts/unpack_vot.sh: 没有那个文件或目录

Traceback (most recent call last):
  File "process_dataset_traj.py", line 230, in <module>
    main()
  File "process_dataset_traj.py", line 52, in main
    output_file = h5py.File(args.dataset_path)
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/FMODetect/dataset/votfmomedtraj_inputs.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

Please let me summarize this problems:
 1.I think that i git `git clone --recursive [git@github.com](mailto:git@github.com):rozumden/FMODetect.git`,  I only get empty folders `trackdat`, so I won't download the VOT dataset for background images, which is why I can not be able to run `process_dataset_traj.py`. 
2. Do I need to prepare these two documents by myself?  `download_vot.sh` and` unpack_vot.sh`
 Sir, can u give me some advice. THANK U!

**Comment by rozumden** [comment]
If your trackdat folder is empty, then you could try to directly download/clone it from https://github.com/jvlmdr/trackdat

 Regarding your question about being unable to open the hdf5 file, I've made some changes and it should work now. Probably, your h5py version is different, but this change should work with any version.

**Comment by Gi-gigi** [comment]
Thank u sir @rozumden give me advice.
I met another problem, i think it is not my personal problem.
 I `git clone --recursive [git@github.com](mailto:git@github.com):rozumden/FMODetect.git` agian. Meanwhile, I download `trackdar` folder in h[ttps://github.com/jvlmdr/trackdat](url)
 when i `sudo bash generate_dataset.sh`
Problem occurred：
```
trackdat/scripts/download_vot.sh: line 19: jq: command not found
trackdat/scripts/download_vot.sh: line 20: jq: command not found
trackdat/scripts/download_vot.sh: line 21: jq: command not found
extract "dl/vot/annotations/bag.zip"
FileNotFoundError: [Errno 2] No such file or directory: 'dl/vot/annotations/bag.zip'
```
This problem causes the resulting folder in the` dl /vot `folder to be empty, and the `annotations.txt, color.txt and list.txt` are also empty.
I've looked up a lot of sources and haven't solved this problem. 
Then I did a test and downloaded the dataset directly from the website [https://github.com/jvlmdr/trackdat](https://github.com/jvlmdr/trackdat )
but the above error still occurred `trackdat/scripts/download_vot.sh: line 19,20,21:command not found`. I think there is a problem here, so` bag.zip `cannot be extracted later.
I don't know how others succeeded in downloading it. I couldn't download it anyway.

 Thank u again.

**Comment by Gi-gigi** [comment]
> Thank u sir @rozumden give me advice. I met another problem, i think it is not my personal problem. I `git clone --recursive [git@github.com](mailto:git@github.com):rozumden/FMODetect.git` agian. Meanwhile, I download `trackdar` folder in h[ttps://github.com/jvlmdr/trackdat](url) when i `sudo bash generate_dataset.sh` Problem occurred：
> 
> ```
> trackdat/scripts/download_vot.sh: line 19: jq: command not found
> trackdat/scripts/download_vot.sh: line 20: jq: command not found
> trackdat/scripts/download_vot.sh: line 21: jq: command not found
> extract "dl/vot/annotations/bag.zip"
> FileNotFoundError: [Errno 2] No such file or directory: 'dl/vot/annotations/bag.zip'
> ```
> 
> This problem causes the resulting folder in the`dl /vot`folder to be empty, and the `annotations.txt, color.txt and list.txt` are also empty. I've looked up a lot of sources and haven't solved this problem. Then I did a test and downloaded the dataset directly from the website https://github.com/jvlmdr/trackdat but the above error still occurred `trackdat/scripts/download_vot.sh: line 19,20,21:command not found`. I think there is a problem here, so`bag.zip`cannot be extracted later. I don't know how others succeeded in downloading it. I couldn't download it anyway.
> 
> Thank u again.

I solved it, run `sudo apt-get install jq`

**Comment by Gi-gigi** [comment]
Thanks sir very very much  , I ran it successfully!  I will close this question
