### ISSUE TITLE
Inference infos

### ISSUE THREAD

**Issue by lorenzoloretucci** [rozumden/FMODetect#3]
Hi! I found this repository reading the official paper, it was a very interesting paper! 
I want to know how perform your architecture for a specific ball object into a moving scenario. To be more precise I want to track a small ball into a foosball table. 
Do you have any advise? 
Thanks :)

**Comment by rozumden** [comment]
Hi, thanks! Have you just tried running this codebase on your data? It could work as it is. Some problems can arise if your ball is too small (a few pixels) or the camera is shaking a lot. On the other hand, you can also finetune this architecture to a single specific ball, e.g. by setting the thresholds or even retraining. You can also share your data with me, and I can take a look.
Best,
Denys
